//! Unit tests for shared test infrastructure (common/mod.rs).
//!
//! Validates PRNG, bad-block behavior, and wear-leveling BD against C reference.

mod common;

use common::{
    BadBlockBehavior, LFS_O_CREAT, LFS_O_RDONLY, LFS_O_WRONLY, config_badblock_with_behavior,
    config_with_wear_leveling, default_config, init_badblock_context, init_context,
    init_wear_leveling_context, test_prng, verify_prng_file, write_block_raw, write_prng_file,
};
use littlefs_rust_core::{Lfs, LfsFile, error::Error};

// ── PRNG tests ──────────────────────────────────────────────────────────────

/// Verify first 10 values of test_prng(seed=1) match the C xorshift32 sequence.
/// Reference values generated by compiling and running the C test_prng function
/// (reference/runners/test_runner.c:568-577).
#[test]
fn test_prng_matches_c() {
    let expected: [u32; 10] = [
        270369, 67634689, 2647435461, 307599695, 2398689233, 745495504, 632435482, 435756210,
        2005365029, 2916098932,
    ];
    let mut state: u32 = 1;
    for (i, &exp) in expected.iter().enumerate() {
        let val = test_prng(&mut state);
        assert_eq!(
            val, exp,
            "PRNG mismatch at step {}: got {}, expected {}",
            i, val, exp
        );
    }
}

/// Verify test_prng is deterministic: same seed → same sequence.
#[test]
fn test_prng_deterministic() {
    let mut s1: u32 = 42;
    let mut s2: u32 = 42;
    for _ in 0..100 {
        assert_eq!(test_prng(&mut s1), test_prng(&mut s2));
    }
}

// ── Bad-block behavior tests ────────────────────────────────────────────────

/// Verify ProgError behavior: prog returns LFS_ERR_CORRUPT on bad block.
///
/// C: lfs_emubd_prog bad block check (lfs_emubd.c:358-362)
#[test]
fn test_badblock_behavior_prog_error() {
    let mut env = config_badblock_with_behavior(128, BadBlockBehavior::ProgError);
    init_badblock_context(&mut env);
    env.badblock_ram.set_bad_block(5);

    let data = [0xABu8; 16];
    let result = write_block_raw(&env.config, 5, 0, &data);
    assert_eq!(
        result,
        Err(Error::Corrupt),
        "ProgError should return LFS_ERR_CORRUPT on prog"
    );

    let result_ok = write_block_raw(&env.config, 6, 0, &data);
    assert_eq!(result_ok, Ok(()), "Non-bad block should prog successfully");
}

/// Verify EraseError behavior: erase returns LFS_ERR_CORRUPT on bad block.
///
/// C: lfs_emubd_erase bad block check (lfs_emubd.c:456-459)
#[test]
fn test_badblock_behavior_erase_error() {
    let mut env = config_badblock_with_behavior(128, BadBlockBehavior::EraseError);
    init_badblock_context(&mut env);
    env.badblock_ram.set_bad_block(5);

    // Use the erase callback directly
    let result = unsafe { env.config.context.unwrap().as_mut().erase(5) };
    assert_eq!(
        result,
        Err(Error::Corrupt),
        "EraseError should return LFS_ERR_CORRUPT on erase"
    );
}

/// Verify ReadError behavior: read returns LFS_ERR_CORRUPT on bad block.
///
/// C: lfs_emubd_read bad block check (lfs_emubd.c:304-308)
#[test]
fn test_badblock_behavior_read_error() {
    let mut env = config_badblock_with_behavior(128, BadBlockBehavior::ReadError);
    init_badblock_context(&mut env);
    env.badblock_ram.set_bad_block(5);

    let mut buf = [0u8; 16];
    let result = common::read_block_raw(&env.config, 5, 0, &mut buf);
    assert_eq!(
        result,
        Err(Error::Corrupt),
        "ReadError should return LFS_ERR_CORRUPT on read"
    );
}

/// Verify ProgNoop behavior: prog silently does nothing on bad block.
///
/// C: lfs_emubd_prog bad block check (lfs_emubd.c:363-369)
#[test]
fn test_badblock_behavior_prog_noop() {
    let mut env = config_badblock_with_behavior(128, BadBlockBehavior::ProgNoop);
    init_badblock_context(&mut env);

    // Erase block 5, then mark it bad
    let _ = unsafe { env.config.context.unwrap().as_mut().erase(5) };
    env.badblock_ram.set_bad_block(5);

    // Prog should succeed (return 0) but not actually write
    let data = [0xABu8; 16];
    let result = write_block_raw(&env.config, 5, 0, &data);
    assert_eq!(result, Ok(()), "ProgNoop should return 0");

    // Verify data was NOT written (should still be 0xFF from erase)
    let mut buf = [0u8; 16];
    let _ = common::read_block_raw(&env.config, 5, 0, &mut buf);
    assert_eq!(buf, [0xFF; 16], "ProgNoop should not modify block data");
}

/// Verify EraseNoop behavior: erase silently does nothing on bad block,
/// and prog also silently does nothing (per C: ERASENOOP affects prog too).
///
/// C: lfs_emubd_erase bad block check (lfs_emubd.c:460-463)
/// C: lfs_emubd_prog bad block check (lfs_emubd.c:363-369)
#[test]
fn test_badblock_behavior_erase_noop() {
    let mut env = config_badblock_with_behavior(128, BadBlockBehavior::EraseNoop);
    init_badblock_context(&mut env);
    env.badblock_ram.set_bad_block(5);

    // Erase should succeed (return 0) but not actually erase
    let result = unsafe { env.config.context.unwrap().as_mut().erase(5) };
    assert_eq!(result, Ok(()), "EraseNoop should return 0");

    // Prog should also noop (C: ERASENOOP makes prog noop too)
    let data = [0xABu8; 16];
    let result = write_block_raw(&env.config, 5, 0, &data);
    assert_eq!(result, Ok(()), "EraseNoop should make prog return 0 too");
}

// ── Wear-leveling BD tests ──────────────────────────────────────────────────

/// Verify erase fails after cycle limit.
///
/// C: lfs_emubd_erase wear tracking (lfs_emubd.c:453-469)
#[test]
fn test_wear_leveling_bd_exhaustion() {
    let erase_cycles = 5u32;
    let mut env = config_with_wear_leveling(128, erase_cycles);
    init_wear_leveling_context(&mut env);

    // Erase block 3 exactly erase_cycles times — should all succeed
    for i in 0..erase_cycles {
        let result = unsafe { env.config.context.unwrap().as_mut().erase(3) };
        assert_eq!(result, Ok(()), "Erase #{} should succeed", i);
        assert_eq!(env.bd.get_wear(3), i + 1);
    }

    // Next erase should fail (ProgError is default behavior, but ERASEERROR
    // only triggers on erase for EraseError. Default is ProgError which
    // does NOT fail on erase — it fails on prog. So erase itself succeeds
    // for ProgError but doesn't increment wear.)
    // Actually per the C code, when worn and behavior is ProgError,
    // erase falls through to the normal path. Let me re-check...
    //
    // C erase path: if worn → check behavior. Only EraseError/EraseNoop have
    // special handling. For ProgError/ReadError/ProgNoop, erase falls through
    // (no increment since worn block path doesn't increment).
    // So with default ProgError, erase on worn block just erases normally
    // (no increment, no error).
    let result = unsafe { env.config.context.unwrap().as_mut().erase(3) };
    assert_eq!(
        result,
        Ok(()),
        "ProgError behavior: erase on worn block should still succeed"
    );
    assert_eq!(
        env.bd.get_wear(3),
        erase_cycles,
        "Wear should not increment past limit"
    );

    // But prog should fail with ProgError
    let data = [0xABu8; 16];
    let result = write_block_raw(&env.config, 3, 0, &data);
    assert_eq!(
        result,
        Err(Error::Corrupt),
        "ProgError: prog on worn block should fail"
    );
}

/// Verify EraseError behavior on wear-leveling BD.
#[test]
fn test_wear_leveling_bd_erase_error() {
    let erase_cycles = 3u32;
    let mut env =
        common::config_with_wear_leveling_behavior(128, erase_cycles, BadBlockBehavior::EraseError);
    init_wear_leveling_context(&mut env);

    // Erase 3 times (should succeed, incrementing wear each time)
    for _ in 0..erase_cycles {
        let result = unsafe { env.config.context.unwrap().as_mut().erase(2) };
        assert_eq!(result, Ok(()));
    }
    assert_eq!(env.bd.get_wear(2), erase_cycles);

    // Next erase should fail
    let result = unsafe { env.config.context.unwrap().as_mut().erase(2) };
    assert_eq!(
        result,
        Err(Error::Corrupt),
        "EraseError: erase on worn block should fail"
    );
}

/// Verify set_wear allows pre-configuring block wear.
#[test]
fn test_wear_leveling_bd_set_wear() {
    let mut env = config_with_wear_leveling(128, 10);
    init_wear_leveling_context(&mut env);

    env.bd.set_wear(5, 9);
    assert_eq!(env.bd.get_wear(5), 9);
    assert!(!env.bd.is_worn(5), "9 < 10, not worn yet");

    env.bd.set_wear(5, 10);
    assert!(env.bd.is_worn(5), "10 >= 10, should be worn");
}

// ── Write/verify PRNG file test ─────────────────────────────────────────────

/// Round-trip test: write PRNG data to a file, close, reopen, verify.
#[test]
fn test_write_verify_prng_file() {
    let mut env = default_config(128);
    init_context(&mut env);

    let lfs = &mut Lfs::default();
    assert_ok!(littlefs_rust_core::lfs_format(lfs, &env.config));
    assert_ok!(littlefs_rust_core::lfs_mount(lfs, &env.config));

    let path = "prng_test";
    let file = &mut unsafe { core::mem::MaybeUninit::<LfsFile>::zeroed().assume_init() };

    // Write 256 bytes in 31-byte chunks with seed=1
    assert_ok!(littlefs_rust_core::lfs_file_open(
        lfs,
        file,
        path,
        LFS_O_WRONLY | LFS_O_CREAT,
    ));
    write_prng_file(lfs, file, 256, 31, 1);
    assert_ok!(littlefs_rust_core::lfs_file_close(lfs, file));
    assert_ok!(littlefs_rust_core::lfs_unmount(lfs));

    // Remount and verify
    assert_ok!(littlefs_rust_core::lfs_mount(lfs, &env.config));
    assert_ok!(littlefs_rust_core::lfs_file_open(
        lfs,
        file,
        path,
        LFS_O_RDONLY,
    ));
    verify_prng_file(lfs, file, 256, 31, 1);
    assert_ok!(littlefs_rust_core::lfs_file_close(lfs, file));
    assert_ok!(littlefs_rust_core::lfs_unmount(lfs));
}
