//! Unit tests for shared test infrastructure (common/mod.rs).
//!
//! Validates PRNG, bad-block behavior, and wear-leveling BD against C reference.

mod common;

use common::{
    LFS_O_CREAT, LFS_O_RDONLY, LFS_O_WRONLY, test_prng, verify_prng_file, write_prng_file,
};
use littlefs_rust_core::{Lfs, LfsConfig, LfsFile};
use littlefs_rust_test_macro::lfs_test;

// ── PRNG tests ──────────────────────────────────────────────────────────────

/// Verify first 10 values of test_prng(seed=1) match the C xorshift32 sequence.
/// Reference values generated by compiling and running the C test_prng function
/// (reference/runners/test_runner.c:568-577).
#[test]
fn test_prng_matches_c() {
    let expected: [u32; 10] = [
        270369, 67634689, 2647435461, 307599695, 2398689233, 745495504, 632435482, 435756210,
        2005365029, 2916098932,
    ];
    let mut state: u32 = 1;
    for (i, &exp) in expected.iter().enumerate() {
        let val = test_prng(&mut state);
        assert_eq!(
            val, exp,
            "PRNG mismatch at step {}: got {}, expected {}",
            i, val, exp
        );
    }
}

/// Verify test_prng is deterministic: same seed → same sequence.
#[test]
fn test_prng_deterministic() {
    let mut s1: u32 = 42;
    let mut s2: u32 = 42;
    for _ in 0..100 {
        assert_eq!(test_prng(&mut s1), test_prng(&mut s2));
    }
}

// ── Write/verify PRNG file test ─────────────────────────────────────────────

/// Round-trip test: write PRNG data to a file, close, reopen, verify.
#[lfs_test]
fn test_write_verify_prng_file(cfg: &LfsConfig) {
    let lfs = &mut Lfs::default();
    assert_ok!(littlefs_rust_core::lfs_format(lfs, cfg));
    assert_ok!(littlefs_rust_core::lfs_mount(lfs, cfg));

    let path = "prng_test";
    let file = &mut LfsFile::default();

    // Write 256 bytes in 31-byte chunks with seed=1
    assert_ok!(littlefs_rust_core::lfs_file_open(
        lfs,
        file,
        path,
        LFS_O_WRONLY | LFS_O_CREAT,
    ));
    write_prng_file(lfs, file, 256, 31, 1);
    assert_ok!(littlefs_rust_core::lfs_file_close(lfs, file));
    assert_ok!(littlefs_rust_core::lfs_unmount(lfs));

    // Remount and verify
    assert_ok!(littlefs_rust_core::lfs_mount(lfs, cfg));
    assert_ok!(littlefs_rust_core::lfs_file_open(
        lfs,
        file,
        path,
        LFS_O_RDONLY,
    ));
    verify_prng_file(lfs, file, 256, 31, 1);
    assert_ok!(littlefs_rust_core::lfs_file_close(lfs, file));
    assert_ok!(littlefs_rust_core::lfs_unmount(lfs));
}
